package com.linhtetko.themoviebookingapp.dummy

/*
val seatList = listOf(
    SeatVO("A", SEAT_TEXT),
    SeatVO(type = SEAT_SPACE),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO(type = SEAT_SPACE),
    SeatVO("A", SEAT_TEXT),
    SeatVO("B", SEAT_TEXT),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO("B", SEAT_TEXT),
    SeatVO("C", SEAT_TEXT),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO("C", SEAT_TEXT),
    SeatVO("D", SEAT_TEXT),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO("D", SEAT_TEXT),
    SeatVO("E", SEAT_TEXT),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO(type = SEAT_RESERVED),
    SeatVO(type = SEAT_RESERVED),
    SeatVO(type = SEAT_RESERVED),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO("E", SEAT_TEXT),
    SeatVO("F", SEAT_TEXT),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO("F", SEAT_TEXT),
    SeatVO("G", SEAT_TEXT),
    SeatVO(type = SEAT_SPACE),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO(type = SEAT_AVAILABLE),
    SeatVO(type = SEAT_SPACE),
    SeatVO("G", SEAT_TEXT),
)
 */